### ISSUE TITLE
Build instructions for the SDMA assembler

### ISSUE THREAD

**Issue by ceggers-arri** [bsh-git/SDMA_assembler#1]
Thanks for sharing the SDMA assembler. Unfortunately I am not able to build it. I have no experience with Haskell, so I tried the instructions below. Maybe some sources files are missing in GIT?

> curl -sSL https://get.haskellstack.org/ | sh
> git clone https://github.com/bsh-git/SDMA_assembler.git
> cd SDMA_assembler/
> stack init
> stack build
Building all executables for `sdma-assembler' once. After a successful build of all of them, only specified executables will be rebuilt.
sdma-assembler> configure (lib + exe)
Configuring sdma-assembler-0.1.0.0...
Warning: 'extra-source-files: ../../README.md' is a relative path outside of
the source tree. This will not work when generating a tarball with 'sdist'.
sdma-assembler> build (lib + exe)
Preprocessing library for sdma-assembler-0.1.0.0..
Building library for sdma-assembler-0.1.0.0..
[1 of 5] Compiling Paths_sdma_assembler
[2 of 5] Compiling Sdma.Parser

/home/eggers/Projekte/aes/bsh-git/SDMA_assembler/asm/haskell/src/Sdma/Parser.hs:34:1: error:
    Could not find module ‘Sdma.Base’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
34 | import Sdma.Base
   | ^^^^^^^^^^^^^^^^

--  While building package sdma-assembler-0.1.0.0 (scroll up to its section to see the error) using:
      /home/eggers/.stack/setup-exe-cache/x86_64-linux-tinfo6/Cabal-simple_mPHDZzAJ_3.2.1.0_ghc-8.10.4 --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.2.1.0 build lib:sdma-assembler exe:sdmaasm-exe --ghc-options " -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1

**Comment by bsh-git** [comment]
Thank you for your report.

I have added two missing files, and also add a short instruction to build. 

I hope it lets you try the assembler.

**Comment by ceggers-arri** [comment]
Building the assembler now works fine, thanks. I'll try it soon.

N.B. Did you get my email I sent to your netbsd address?
